language: csharp
solution: OnlineBookingSystem.sln
install:
  - nuget restore OnlineBookingSystem.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
  – xbuild /p:Configuration=Release OnlineBookingSystem.sln
  