language: csharp
solution: "./OnlineBookingSystem.sln"
install:
  – travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./OnlineBookingSystem.sln
  – nuget install NUnit.Runners -OutputDirectory testrunner
script:
  – xbuild /p:Configuration=Release OnlineBookingSystem.sln
  – mono ./testrunner/NUnit.Runners.*/tools/nunit-console.exe ./OBS.Test/obj/Release/OBS.Test.dll