language: csharp
solution: "./OnlineBookingSystem.sln"
install:
  – travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./OnlineBookingSystem.sln
#  – nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  – xbuild ./OnlineBookingSystem.sln
  – mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./OnlineBookingSystem/bin/Release/TravisSample.Test.dll